services:
  faster-whisper:
    image: fedirz/faster-whisper-server:latest-cpu
    container_name: faster-whisper
    restart: unless-stopped
    ports: ["127.0.0.1:8000:8000"]
    environment:
      ASR_MODEL: "Systran/faster-distil-whisper-large-v3"
      ASR_COMPUTE_TYPE: "int8"       # CPU
      ASR_VAD_FILTER: "true"
      ASR_BEAM_SIZE: "3"
      ASR_CHUNK_LENGTH_S: "30"
      LOG_LEVEL: "info"
    volumes:
      - fw_cache:/root/.cache
volumes:
  fw_cache:

